(add-to-list 'load-path "~/.emacs.d/lisp")

(require 'init-basic)
(require 'init-package)
(require 'init-company)
(require 'init-org)
(require 'init-vertico)
(require 'init-eglot)
(require 'init-rust)
(require 'init-yasnippet)
(require 'init-flymake)
(require 'init-go)
(require 'init-window)
(require 'init-plantuml)
